#!/usr/bin/env php
<?php

require_once('ConcordanceFactory.php');

if ( ! isset($argv[1])) {
    die('Usage: concordance /path/to/file');
}

// the second argument is the filepath argument
$filepath = $argv[1];

// generate the concordance with the given filepath
ConcordanceFactory::createEnglishFileScreenInstance($filepath)->generate();
